services:
  postgres:
    image: postgres:17
    container_name: cinemaflow-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cinemaflow
      POSTGRES_USER: cinemaflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - cinemaflow_postgres_data:/var/lib/postgresql/data

volumes:
  cinemaflow_postgres_data:
